=== IyaneG10/Moteur-de-workflows-en-C/AJAC_S8/Models/process.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/process" xmlns:tns="http://www.example.org/process" elementFormDefault="qualified">

	
	<element name="process" type="tns:processType"/>

	<complexType name="processType">
		<sequence>
			<element ref="tns:description" minOccurs="0" maxOccurs="1"/>
			<element name="variableList" type="tns:variableListType" minOccurs="0" maxOccurs="1"/>
			<element name="activityList" type="tns:activityListType" minOccurs="1" maxOccurs="1"/>
			<element name="transitionList" type="tns:transitionListType" minOccurs="0" maxOccurs="1"/>
		</sequence>
		<attribute name="name" type="string" />
	</complexType>
	
 

    <element name="description" type="string"></element>
   
    <element name="performer" type="string"></element>

    <complexType name="transitionListType">
    	<sequence>
    		<element name="transition" type="tns:transitionType" minOccurs="0" maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>
    
    <complexType name="activityListType">
    	<sequence>
    		<element name="activity" type="tns:activityType" minOccurs="1" maxOccurs="unbounded"/>
    	</sequence>
    </complexType>

	<complexType name="variableListType">
    	<sequence>
    		<element name="variable" type="tns:variableType" minOccurs="0" maxOccurs="unbounded"/>
    	</sequence>
    </complexType>


    

    <complexType name="transitionType">
    	<sequence>
    		<element name="condition" type="tns:conditionType" minOccurs="0" maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="to" type="string"></attribute>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="from" type="string"></attribute>
    </complexType>

    <complexType name="activityType">
    	<sequence>
    		<element ref="tns:description" minOccurs="0" maxOccurs="1"/>
    		<element ref="tns:performer" minOccurs="1" maxOccurs="1"/>
    		<element name="input" type="tns:ioType" minOccurs="0" maxOccurs="unbounded"/>
    		<element name="output" type="tns:ioType" minOccurs="0" maxOccurs="unbounded"/>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="name" type="string"></attribute>
    </complexType>
    
    <complexType name="ioType">
    	<attribute name="name"/>
    </complexType>
    
    <complexType name="variableType">
    	<attribute name="name" type="string" />
    	<attribute name="type" type="tns:types" />
    	<attribute name="initialValue" type="string" />
    </complexType>

    <complexType name="conditionType">
		<attribute name="expr" type="string"/>
	</complexType>    

	<simpleType name="types">
		<restriction base="string">
			<enumeration value="int"/>
			<enumeration value="string"/>
			<enumeration value="bool"/>
		</restriction>
	</simpleType>
	
</schema>

=== IyaneG10/Moteur-de-workflows-en-C/AJAC_S8/Models/process1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:process xmlns:tns="http://www.example.org/process" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/process process.xsd ">
  <tns:description>Processus stage</tns:description>
  <tns:variableList>
  	<tns:variable name="description_stage" type="string" />
  	<tns:variable name="validation" type="bool" initialValue="false" />
  </tns:variableList>
  <tns:activityList>
    <tns:activity id="A1" name="Demande">
    	<tns:description>Remplir la demande de stage</tns:description>
    	<tns:performer>tmv</tns:performer>
    	<tns:output name="description_stage" />
    </tns:activity>
    <tns:activity id="A2" name="Etude_demande">
    	<tns:description>Etude de la demande de stage</tns:description>
    	<tns:performer>rex</tns:performer>
    	<tns:input >description_stage</tns:input>
    	<tns:output >validation</tns:output>
    </tns:activity>
    <tns:activity id="A3" name="Refus">
    	<tns:description>Demande de stage refuse</tns:description>
    	<tns:performer>tmv</tns:performer>
    </tns:activity>
    <tns:activity id="A4" name="Redaction">
    	<tns:description>Redaction de la convention de stage</tns:description>
    	<tns:performer>nd</tns:performer>
    </tns:activity>
    <tns:activity id="A5" name="Signature">
    	<tns:description>Signature de la convention par l'etudiant</tns:description>
    	<tns:performer>tmv</tns:performer>
    </tns:activity>
    <tns:activity id="A6" name="Signature" >
    	<tns:description>Signature de la convention par l'entreprise</tns:description>
    	<tns:performer>HAL</tns:performer>
    </tns:activity>
    <tns:activity id="A7" name="Signature">
    	<tns:description>Signature de la convention par l'ecole</tns:description>
    	<tns:performer>nd</tns:performer>
    </tns:activity>
  </tns:activityList>
  <tns:transitionList>
  	<tns:transition id="T1" from="A1" to="A2"></tns:transition>
  	<tns:transition id="T2" from="A2" to="A3">
  		<tns:condition expr="validation==false"/>
  	</tns:transition>
  	<tns:transition id="T3" from="A2" to="A4">
  		<tns:condition expr="validation==true"/>
  	</tns:transition>
  	<tns:transition id="T4" from="A4" to="A5"></tns:transition>
  	<tns:transition id="T5" from="A5" to="A6"></tns:transition>
  	<tns:transition id="T6" from="A6" to="A7"></tns:transition>
  </tns:transitionList>
</tns:process>
